version: 0.2
phases:
 install:
   commands:
     - echo "install step"
     - npm install
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - npm run build
     - aws s3 sync --delete ./dist/ "s3://drawalot-presentation"
 post_build:
   commands:
     - echo "post_build step"
